Interim commit

diff --git a/m10k b/m10k
--- a/m10k
+++ b/m10k
@@ -7,6 +7,10 @@
 
 # --- Cleanup function
 
+function debug() {
+	echo "==== $(date) == $1" >&2
+}
+
 function cleanup() {
 	rm "$TEMPDIR" "$TEMPPARSE" "$TEMPPERMUTE" "$TEMPRESULT" 2>/dev/null
 	exit 0
@@ -31,6 +35,7 @@ mkdir -p $TEMPDIR
 cd $TEMPDIR
 
 # Explode the tarball
+debug "Exploding tarball"
 tar xf "$TARBALL"
 if [ "$?" -ne 0 ]
 then
@@ -62,6 +67,7 @@ BENCHMARKS=4
 
 # --- Parse options file
 
+debug "Parsing options file"
 ${M10KDIR}/m10k_parse >$TEMPPARSE
 if [ $? != 0 ]
 then
@@ -71,6 +77,7 @@ fi
 
 # --- Permute Options
 
+debug "Permuting Options"
 ${M10KDIR}/m10k_permute >$TEMPPERMUTE <$TEMPPARSE
 if [ $? != 0 ]
 then
@@ -80,14 +87,18 @@ fi
 
 # --- Loop through the permutations
 
+PERM=0
+
 cat "$TEMPPERMUTE"|
 while read PERMUTATION
 do
 
+debug "Processing permutation $((++PERM))"
 # --- Build with selected options
 
 echo "=== Building"
 
+debug "Building"
 ${M10KDIR}/m10k_build <<<$PERMUTATION
 if [ $? != 0 ]
 then
@@ -97,23 +108,25 @@ fi
 
 # --- Test for successful build
 
-echo "=== Testing build"
+debug "Testing build"
 
 ${M10KDIR}/m10k_test
 if [ $? != 0 ]
 then
-	echo "$0: m10k_build failed." >&2
+	echo "$0: m10k_test failed." >&2
 	exit 6
 else
 
 # --- Loop through benchmark runs
 
+debug "Starting benchmarking"
+
 for ((I=0; I<$BENCHMARKS; I++))
 do
 
-# --- Perform Benchmark
+debug "Benchmark run $I"
 
-echo "=== Starting benchmark run $I"
+# --- Perform Benchmark
 
 echo "$TEMPRESULTS"|${M10KDIR}/m10k_benchmark
 if [ $? != 0 ]
@@ -122,8 +135,6 @@ then
 fi
 
 done # loop through benchmark runs
-
-echo "=== Done benchmark runs"
 
 fi # m10k build success/run benchmarks
 
@@ -139,6 +150,8 @@ then
 fi
 
 # --- Tidy and exit
+
+debug "Finished"
 
 cleanup
 exit 0
diff --git a/m10k_test b/m10k_test
--- a/m10k_test
+++ b/m10k_test
@@ -1,26 +1,22 @@
 #!/bin/bash
 
-cd *
-
 #read location of the start-up script
 
 read LOC
 
-echo "Checking if the testing plugin exists"
-
-ls -l m10k_test_plugin 2 > /dev/null
+echo "Checking if the testing plugin exists" >&2
 
 #look for test plugin
-if [ "$?" == 2 ]
-	then
-		echo "$0" plugin not found"
-		exit 2
-	fi
+if [ ! -x "./m10k_test_plugin" ]
+then
+	echo "$0: test plugin '$(pwd)/m10k_test_plugin' not found" >&2
+	exit 2
+fi
 
 
 #if plugin exists then run it
 #pass location of startup script as STDIN
 
+echo "Running test plugin" >&2
 ./m10k_test_plugin <<< $LOC
 
-exit 0
